### ISSUE TITLE
manifest files

### ISSUE THREAD

**Issue by rfht** [moon-chilled/openfmod#2]
Hi,

Any updates or hints on how to create the manifest (.json) files?

Thanks!

**Comment by moon-chilled** [comment]
I generated them using a really hacky script that linked to the real fmod.  It didn't work right, because fmod's api doesn't expose all the information that you need.  So better to actually reverse-engineer the file format and figure out how to get that information from its proper source.

**Comment by moon-chilled** [comment]
that said https://0x0.st/-YFD.c use at your own discretion!

**Comment by moon-chilled** [comment]
oh, wow, that thing is even more of a hack than I remembered.  The lib doesn't expose _any_ information directly, but it comes with logging info; so slurp the info from the log messages.  Dumbest thing ever.  Also looks at line numbers for filtering, so dependent on fmod lib version.

**Comment by rfht** [comment]
Thanks... ugh.

**Comment by rfht** [comment]
Based on the Celeste .json files, I'm wondering if an alternative would be a (fast) name matching.
```
"path": "event:/ui/world_map/whoosh/900ms_forward"
"filename": "ui_world_whoosh_0900ms_forward",

"path": "event:/ui/world_map/whoosh/700ms_forward",
"filename": "ui_world_whoosh_0700ms_forward_01",

"path": "event:/char/badeline/boss_prefight_getup",
"filename": "char_bad_boss_prefightgetup"
```
It's not exact, but close enough that when the game looks for the event in "path", maybe a reimplementation can find the closest match among the filenames...

**Comment by rfht** [comment]
I'm wondering if it's possible to check for encryption... https://forum.xentax.com/viewtopic.php?t=16059
